name: CD Deploy URL Shortener (Simulado)

on:
  workflow_run:
    workflows: ["CI URL Shortener"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Simular despliegue Backend
        run: |
          echo "Desplegando backend..."
          echo "Backend desplegado correctamente (simulado)."

      - name: Simular despliegue Frontend
        run: |
          echo "Desplegando frontend..."
          echo "Frontend desplegado correctamente (simulado)."

      - name: Verificación final
        run: |
          echo "Aplicación URL Shortener desplegada correctamente (simulado)."
